server:
  port: 8089
spring:  application:    name: config-server  cloud:    config:
      label: master
      server:
        git:
          search-paths: 
          - all_config          - all_config/*  
          uri: http://192.168.20.26:8900/chaigy/config_server.git
          username: chaigy
          password: 123456789eureka:  client:    service-url:      defaultZone: http://127.0.0.1:8081/eureka/